name: deno2-nestjs-example

services:
  api:
    container_name: server
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3000"
    networks:
      - main

networks:
  main:
    driver: bridge
